version: '31.0'

services:
  app:
    image: python:3.9
    container_name: my-python-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    command: python app.py
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: my-postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"

volumes:
  db_data: {}